spring:
  data:
    mongodb:
      username: vinycius
      password: vinycius
      host: localhsot
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
