services:
  postgres_product:
    container_name: postgres_microservice_product
    image: postgres:latest
    environment:
      - POSTGRES_USER=vinycius
      - POSTGRES_PASSWORD=vinycius
      - POSTGRES_DB=product
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - postgres_volume_product:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  postgres_order:
    container_name: postgres_microservice_order
    image: postgres:latest
    environment:
      - POSTGRES_USER=vinycius
      - POSTGRES_PASSWORD=vinycius
      - POSTGRES_DB=order
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - postgres_volume_order:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  postgres_payment:
    container_name: postgres_microservice_payment
    image: postgres:latest
    environment:
      - POSTGRES_USER=vinycius
      - POSTGRES_PASSWORD=vinycius
      - POSTGRES_DB=payment
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - postgres_volume_payment:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - microservices-net
    restart: unless-stopped


  mongodb:
    container_name: mongo_microservice
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=vinycius
      - MONGO_INITDB_ROOT_PASSWORD=vinycius
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data

  mail-dev:
    container_name: email_microservice
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"
    networks:
      - microservices-net

  kafka:
    container_name: microservice-kafka
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
   
volumes:
  postgres_volume_product:
  postgres_volume_order:
  mongodb_volume: